autoload colors; colors

BG="%{%F{8}%}"
INVISIBLE="%{%F{0}%}"
BASE01="%{%F{10}%}"
BASE00="%{%F{11}%}"
BASE0="%{%F{12}%}"
GRAY="%{%F{14}%}"
WHITE="%{%F{7}%}"
LIGHT="%{%F{15}%}"
YELLOW="%{%F{3}%}"
ORANGE="%{%F{9}%}"
RED="%{%F{1}%}"
MAGENTA="%{%F{5}%}"
VIOLET="%{%F{13}%}"
BLUE="%{%F{4}%}"
CYAN="%{%F{6}%}"
GREEN="%{%F{2}%}"
